sonar.organization=clarvia-org
sonar.projectKey=clarvia-org_clarvia-graph

sonar.sources=packages
sonar.tests=packages,tests
sonar.test.inclusions=**/*.test.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**
sonar.coverage.exclusions=**/*.test.ts,**/*.d.ts
