url: "https://guichet.public.lu/fr/citoyens/sante/fin-vie/deces/declaration-deces.html"
captured_at: "2026-06-05T18:37:16Z"
capture_method: manual_download
captured_by: contributor.Talizdo
language: fr   # fr = French (required), en = English (optional), de = German (optional)
page_title: "Déclaration du décès d'un proche - Guichet.lu - Luxembourg"
