id: form.lu.cnap.survivor_pension_application
schema_version: "0.1.0"
title: Demander une pension de survie
title_en: Apply for a survival pension
description: CNAP form for survivor pension in case of spouse or partner death.
jurisdiction: LU
jurisdiction_uri: http://publications.europa.eu/resource/authority/country/LUX
authority_refs:
- authority.lu.cnap
url: https://cnap.public.lu/fr/documentation/formulaires.html
languages:
- fr
- de
- en
form_role: blank_template
authoring_status: approved
distribution_status: public_open
record_valid_from: '2026-06-05'
record_valid_to: null
