# SPDX-FileCopyrightText: 2025-2026 CLARVIA ASBL, Luxembourg
# SPDX-License-Identifier: EUPL-1.2

name: REUSE Compliance

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  reuse:
    name: REUSE lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: REUSE compliance check
        uses: fsfe/reuse-action@676e2d560c9a403aa252096d99fcab3e1132b0f5 # v6.0.0
